e_commerce_project/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

e_commerce_project/e_commerce_app/urls.py
from django.urls import path
from . import views
app_name='e_commerce_app'
urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

e_commerce_project/e_commerce_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from e_commerce_app import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('e_commerce_app/',include('e_commerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce_project/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

e_commerce_project/cart/models.py
from django.db import models
from e_commerce_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

e_commerce_project/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from e_commerce_app.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save();
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
    cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

e_commerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" >
    <link rel="stylesheet" href="{% static 'css/custom.css'%}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

e_commerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to the our ms-cart and here we providing you the world of great shopping experience of somany branded collections.
{% endblock %}
{% block title %}
    Cart - Shop Your Favourate !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your shopping cart is empty
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'e_commerce_app:allProdCat' %}">Here</a>
            </p>
        </div>
    </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5" >Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="crt_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image" style="width:50px;height:50px;"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Unit Price : {{cart_item.product.price}}
                    QTY: {{cart_item.quantity}} x $ {{cart_item.product.price}}
                </td>
                <td>$ {{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping ms-cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Your total is <strong>$ {{total}}</strong>
            </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'e_commerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
    </div>
</div><br>
{% endif %}
{% endblock %}

e_commerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc  |truncatewords:155 }}
    {% else %}
        Welcome to the our ms-cart and here we providing you the world of great shopping experience of somany branded collections.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-MS CART
    {% else %}
        See Our Collections-MS CART
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'e_commerce_app:allProdCat' %}">MS COLLECTIONS</a>{{category.name}}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
{% else %}
<div>
    <center><img class="my_image my_image_padding" src="{% static 'img/ms-banner.png' %}" style="width:1500px;" alt=""></center>
</div>
<br>
<div>
    <h1 class="text-center my_title">MS CART COLLECTIONS</h1>
    <p class="text-justify">We are providing online shopping facilities throgh our MS-CART. and we have somany collections of many brand items. Footwears,Travlgoods, House-Hold products,Electronic Items are always here with your familir brands.Lets Enjoy...</p>
</div>
{% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}">
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
<div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
</div>
    </div>
</div>
{% endblock %}

e_commerce_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; MS Wholesale and Retail CART</p>
</div>

e_commerce_project/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/ms-logo.png' %}" style="width:70px;height:70px;" alt='this is ms logo'>
    </center>
</div>

e_commerce_project/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="login">
</form>
</body>
</html>

e_commerce_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Collections
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'e_commerce_app:allProdCat' %}">All Products</a>
           {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
      </li>
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--      </li>-->
        {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="/cart/"><i class="fas fa-cart-plus">{{item_count}}</i></a>
      </li>
        {% endif %}
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
      </ul>
        {% if user.is_authenticated %}
        <ul>Hi...{{user.username}}</ul>
      <ul><a class="nav-link" href="logout"><i class="fas fa-sign-out-alt"> Logout</i></a></ul>
        {% else %}
      <ul><a class="nav-link" href="register"><i class="far fa-registered"> Register</i></a></ul>
      <ul><a class="nav-link" href="login"><i class="fas fa-sign-in-alt"> Login</i></a></ul>
        {% endif %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>
<nav>
<!--    <ul>-->
<!--        <li><a href="{% url 'e_commerce_app:allProdCat' %}">All products</a></li>-->
<!--        {% for cat in links %}-->
<!--            <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--        {% endfor %}-->
<!--        <li>your cart</li>-->
<!--    </ul>-->
</nav><br>

e_commerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-MS CART
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'e_commerce_app:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}"></a>{{product.name}}</p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-with:18rem;"></div>
                <img src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b> Out of Stock </b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

e_commerce_project/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
        <input type="text" name="first_name" placeholder="first_name"><br>

        <input type="text" name="last_name" placeholder="last_name"><br>

        <input type="text" name="email" placeholder="email"><br>

        <input type="password" name="password1" placeholder="password"><br>
        <input type="password" name="password2" placeholder="confirm password"><br>
        <input type="submit" value="registration">
</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>
</body>
</html>

e_commerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-MS CART
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> You have Searched for:{{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}">
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}